version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: exness-container
    restart: unless-stopped

    environment:
      POSTGRES_USER: krishhna_dev
      POSTGRES_PASSWORD: Krishhna@0024
      POSTGRES_DB: exness_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
